import streamlit as st
from google.cloud import storage, bigquery
import os

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "autosight-agent-key.json"

# 🎯 Configuration
BUCKET_NAME = "autosight-data"
IMAGE_BLOB_PATH = "trendflow/analysis_plot.png"
SUMMARY_BLOB_PATH = "trendflow/summary.txt"
BQ_TABLE = "autosight.autosight_dataset.airtravel_data"

# 🧠 Title + Description
st.set_page_config(page_title="AutoSight Agents", layout="centered")
st.title("📊 AutoSight Agents Dashboard")
st.markdown("This dashboard displays results generated by your AI data pipeline on GCP.")

# 📥 Load image from GCS
st.subheader("Generated Chart")
storage_client = storage.Client()
bucket = storage_client.bucket(BUCKET_NAME)
image_blob = bucket.blob(IMAGE_BLOB_PATH)
image_blob.download_to_filename("plot.png")
st.image("plot.png", caption="Analysis Plot")

# 📄 Load summary text
st.subheader("AI Summary")
summary_blob = bucket.blob(SUMMARY_BLOB_PATH)
summary_blob.download_to_filename("summary.txt")
with open("summary.txt", "r") as f:
    summary = f.read()
st.code(summary, language="text")

# 🔎 Query BigQuery table
st.subheader("BigQuery Table Preview")
bq_client = bigquery.Client()
query = f"SELECT * FROM `{BQ_TABLE}` LIMIT 10"
df = bq_client.query(query).to_dataframe()
st.dataframe(df)
